---
- hosts: jenkins-master
  become: true
  tasks: 
  - name: download Jenkins repo key 
    apt_key:
      url:  https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
      state: present 

  - name: Add Jenkins repo 
    apt_repository: 
      repo: 'deb https://pkg.jenkins.io/debian-stable binary/'
      state: present 

  - name: install java
    apt: 
      name: openjdk-11-jre
      state: present 

  - name: install jenkins 
    apt: 
      name: jenkins 
      state: present 

  - name: start jenkins service 
    service:
      name: jenkins 
      state: started 
  
  - name: enable jenkins service to start at boot time 
    service: 
      name: jenkins 
      enabled: yes 
